version: "1.0"
name: 自动构建和同步部署
displayName: 自动构建和部署
triggers:
  trigger: auto
  push:
    branches:
      - master # 如果你的默认分支叫 main，请改成 main

stages:
  - name: BuildAndDeploy
    displayName: 构建与部署
    strategy: naturally
    trigger: auto
    steps:
      - step: build@nodejs
        name: 构建静态文件
        displayName: 构建静态文件
        nodeVersion: 20.10.0 # 使用较新的node
        commands:
          - pnpm install || npm install --legacy-peer-deps
          - npm run build
          # Vuepress 会把生成的静态页面放在 docs/.vuepress/dist

      - step: agent-deploy
        name: 部署到1Panel
        displayName: SSH同步至服务器
        hostGroupID: "" # 如果有主机组填入，没有通过普通ssh推
        # 下面使用 Gitee 预置的 SSH 命令将产物传输至 1Panel 目录
        script:
          - scp -r -i $DEPLOY_SSH_KEY -o StrictHostKeyChecking=no ./docs/.vuepress/dist/* root@47.103.74.108:/opt/1panel/apps/openresty/openresty/www/sites/app.jdynb.xyz/index/
